version: "3"
services:
#  db:
#    image: mariadb:10.5.1-bionic
#    restart: always
#    volumes:
#        - db_data:/var/lib/mysql
#    networks:
#        - external_network
#    environment:
#        MYSQL_DATABASE: "directus"
#        MYSQL_USER: "directus"
#        MYSQL_PASSWORD: "directus"
#        MYSQL_ROOT_PASSWORD: "${DIRECTUS_DATABASE_PASSWORD}"
#    command: mysqld --innodb-buffer-pool-size=256M

  directus:
    image: directus/directus:v9.0.0-rc.69
    restart: unless-stopped
    network_mode: "bridge"
    #depends_on:
    #    - db
    ports:
      - "172.17.0.1:${DIRECTUS_API_LISTEN}:8055"
    environment:
      PUBLIC_URL: "${DIRECTUS_PUBLIC_URL}"
      KEY: "${DIRECTUS_KEY}"
      SECRET: "${DIRECTUS_SECRET}"
      DB_CLIENT: 'pg'
      DB_HOST: "${DIRECTUS_DATABASE_HOST}"
      DB_PORT: "${DIRECTUS_DATABASE_PORT}"
      DB_DATABASE: "${DIRECTUS_DATABASE_NAME}"
      DB_USER: "${DIRECTUS_DATABASE_USERNAME}"
      DB_PASSWORD: "${DIRECTUS_DATABASE_PASSWORD}"
      EMAIL_FROM: "${SMTP_FROM}"
      EMAIL_TRANSPORT: 'smtp'
      EMAIL_SMTP_HOST: "${SMTP_HOST}"
      EMAIL_SMTP_PORT: '465'
      EMAIL_SMTP_USER: "${SMTP_USER}"
      EMAIL_SMTP_PASSWORD: "${SMTP_PASSWORD}"
      EMAIL_SMTP_SECURE: 'true'
    #links:
    #    - db:mysql

  penhas_api:
    image: azminas/penhas_api
    restart: unless-stopped
    ports:
      - "172.17.0.1:${PENHAS_API_LISTEN}:8080"
    environment:
      REDIS_SERVER: "${REDIS_SERVER}"
      REDIS_NS: "${REDIS_NS}"
    volumes:
        - ../data/:/data/
        - ./api/:/src/
    networks:
        - external_network
    #depends_on:
    #    - directus
    #links:
    #    - db:mysql

#volumes:
#    db_data: {}
#    penhas_api_data: {}

networks:
    external_network:

# ALTER USER 'directus'@'172.19.0.4' IDENTIFIED WITH mysql_native_password;