version: "3"
services:
  db:
    image: mariadb:10.5.1-bionic
    #restart: always
    volumes:
        - db_data:/var/lib/mysql/data
    environment:
      MYSQL_DATABASE: "directus"
      MYSQL_USER: "directus"
      MYSQL_PASSWORD: "directus"
      MYSQL_ROOT_PASSWORD: "hjdfyudfjkajk"
    ports:
      - "64599:3306"

  directus:
    image: directus/directus:v8-apache
    #restart: always
    depends_on:
        - db
    ports:
      - "8080:80"
    environment:
      DIRECTUS_APP_ENV: "production"
      DIRECTUS_AUTH_PUBLICKEY: "lkj4589hjkklçghj90-sdf5671234hbjdrtg,4mi"
      DIRECTUS_AUTH_SECRETKEY: "dfklçasklçawlçkasdfklçjsdfgu890kmlçdjklçd"
      DIRECTUS_DATABASE_HOST: "mysql"
      DIRECTUS_DATABASE_PORT: "3306"
      DIRECTUS_DATABASE_NAME: "directus"
      DIRECTUS_DATABASE_USERNAME: "directus"
      DIRECTUS_DATABASE_PASSWORD: "hjdfyudfjkajk"
    volumes:
        - ./directus/data/config:/var/directus/config
        - ./directus/data/uploads:/var/directus/public/uploads
    links:
      - db:mysql


volumes:
    db_data: {}

# ALTER USER 'directus'@'172.19.0.4' IDENTIFIED WITH mysql_native_password;