version: "3"
services:
  db:
    image: mariadb:10.5.1-bionic
    restart: always
    volumes:
        - db_data:/var/lib/mysql/data
    environment:
      MYSQL_DATABASE: "directus"
      MYSQL_USER: "directus"
      MYSQL_PASSWORD: "directus"
      MYSQL_ROOT_PASSWORD: "hjdfyudfjkajk"
    ports:
      - "${MYSQL_LISTEN}:3306"

  directus:
    image: directus/directus:v8-apache
    restart: always
    depends_on:
        - db
    ports:
      - "${DIRECTUS_API_LISTEN}:80"
    environment:
      DIRECTUS_APP_ENV: "production"
      DIRECTUS_AUTH_PUBLICKEY: "${DIRECTUS_AUTH_PUBLICKEY}"
      DIRECTUS_AUTH_SECRETKEY: "${DIRECTUS_AUTH_SECRETKEY}"
      DIRECTUS_DATABASE_HOST: "${DIRECTUS_DATABASE_HOST}"
      DIRECTUS_DATABASE_PORT: "${DIRECTUS_DATABASE_PORT}"
      DIRECTUS_DATABASE_NAME: "${DIRECTUS_DATABASE_NAME}"
      DIRECTUS_DATABASE_USERNAME: "${DIRECTUS_DATABASE_USERNAME}"
      DIRECTUS_DATABASE_PASSWORD: "${DIRECTUS_DATABASE_PASSWORD}"
    volumes:
        - ./directus/data/config:/var/directus/config
        - ./directus/data/uploads:/var/directus/public/uploads
    links:
      - db:mysql

  penhas_api:
    image: azminas/penhas_api
    restart: always
    ports:
      - "${PENHAS_API_LISTEN}:80"
    environment:
      REDIS_SERVER: "${REDIS_SERVER}"
      DIRECUTS_API_TOKEN: "${DIRECUTS_API_TOKEN}"
      REDIS_NS: "${REDIS_NS}"
      DIRECUTS_ENDPOINT: "${DIRECUTS_ENDPOINT}"
    volumes:
        - penhas_api_data:/data/
        - ./api/:/src/

    links:
      - directus:directus


volumes:
    db_data: {}
    penhas_api_data: {}


# ALTER USER 'directus'@'172.19.0.4' IDENTIFIED WITH mysql_native_password;